# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba9679caf3ac7eb575095caab25d859185e9e8816c3705d2642ba867877abfe9bb3871f111261ed4fc59ec1231b5dfb919d509388a56a94e333d624e9eea643e

test:
  secret_key_base: 78b3ae5220dc218f7898e8d02e70701fa3b66d27b4f91d65d5ef7b45f6d708ba37be45edeeac184caae7770ab47492037e3021141264943da240cb67cc4968cc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
