---
- name: Install the required packages
  hosts: all
  sudo: True
  vars:
    nodejs_version: 5.x
    apt_keys:
      - 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    apt_repositories:
      - 'deb https://deb.nodesource.com/node_{{ nodejs_version }} trusty main'
    apt_packages:
      - build-essential
      - git
      - nodejs
  tasks:
    - name: Add APT Keys
      apt_key: url="{{ item }}"
      with_items: apt_keys
    - name: Add APT Repositories
      apt_repository: repo="{{ item }}" state=present
      with_items: apt_repositories
    - name: Update cache and upgrade
      apt: update_cache=yes upgrade=safe
    - name: Install missing packages
      apt: name={{ item }}
      with_items: apt_packages
    - name: Install NPM dependencies
      shell: npm install chdir='/vagrant'
      become: vagrant
