---
- name: Install the required packages
  hosts: all
  sudo: True
  vars:
    ruby_version: 2.3
    nodejs_version: 5.x
    apt_keys:
      - 'https://deb.nodesource.com/gpgkey/nodesource.gpg.key'
    apt_repositories:
      - 'ppa:brightbox/ruby-ng'
      - 'deb https://deb.nodesource.com/node_{{ nodejs_version }} trusty main'
    apt_packages:
      - build-essential
      - nodejs
      - ruby{{ ruby_version }}
      - ruby{{ ruby_version }}-dev
      - ruby-switch
    ruby_gems:
      - bundler
  tasks:
    - name: Add APT Keys
      apt_key: url="{{ item }}"
      with_items: apt_keys
    - name: Add APT Repositories
      apt_repository: repo="{{ item }}" state=present
      with_items: apt_repositories
    - name: Update cache and upgrade
      apt: update_cache=yes upgrade=safe
    - name: Install missing packages
      apt: name={{ item }}
      with_items: apt_packages
    - name: Switch to the correct Ruby version
      command: ruby-switch --set ruby{{ ruby_version }}
    - name: Install default Ruby gems
      command: gem install {{ item }}
      with_items: ruby_gems
    - name: Run bundler
      shell: bundle chdir='/vagrant'
      become: vagrant
    - name: Install NPM dependencies
      shell: npm install chdir='/vagrant'
      become: vagrant
